# Generated by Django 3.0.7 on 2020-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('Discription', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(help_text='filled with integer', verbose_name='car price')),
                ('colour_options', models.CharField(choices=[('WH', 'white'), ('BL', 'black'), ('YW', 'yellow'), ('BR', 'brown')], default='white', max_length=2)),
                ('Lunching_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_version', models.DateTimeField(auto_now=True)),
                ('varients', models.TextField(choices=[('PE', 'petrol'), ('DI', 'diesel')])),
            ],
        ),
    ]
