# Generated by Django 3.0.7 on 2020-06-16 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Verna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_selected_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='car name')),
            ],
        ),
        migrations.CreateModel(
            name='selected_car_colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.TextField(verbose_name='car colour')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Verna.selected_car_colour')),
                ('car_name', models.ManyToManyField(to='Verna.final_selected_car')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
