# Generated by Django 3.0.7 on 2020-06-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Verna', '0003_auto_20200616_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='car name')),
                ('details', models.TextField(blank=True, null=True, verbose_name='car details')),
                ('price', models.IntegerField()),
                ('year', models.IntegerField(verbose_name='Launching year')),
                ('Date', models.DateField(verbose_name='Launching date')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_Date', models.DateTimeField(auto_now_add=True)),
                ('Delivery_Date', models.DateTimeField(auto_now=True)),
                ('car_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Verna.CarInformation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner name')),
            ],
        ),
    ]
