# Generated by Django 3.0.7 on 2020-06-23 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Verna', '0004_carinformation_ownerinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinformation',
            name='year',
        ),
        migrations.AddField(
            model_name='carinformation',
            name='design',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Designed By'),
            preserve_default=False,
        ),
    ]
