# Generated by Django 3.0.7 on 2020-07-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verna', '0005_auto_20200623_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerinformation',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
