# Generated by Django 3.0.7 on 2020-07-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Verna', '0007_auto_20200722_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinformation',
            name='color',
        ),
    ]
